#!/bin/bash
# commit
# date YYYY-mm-dd HH:MM:SS
# EXAMPLE: git.sh @~2 '2017-07-12 20:00:00'

commit="$1" datecal="$2"
temp_branch="temp-rebasing-branch"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$(uname)" == "Linux" ]; then
    date_timestamp=$(date -d "$datecal" +%s)
	date_r=$(date -R -d "$datecal")
else
    date_timestamp=$(date -jf "%Y-%m-%d %H:%M:%S" "$datecal" +%s)
    date_r=$(date -R -jf "%Y-%m-%d %H:%M:%S" "$datecal")
fi

echo "datecal=$datecal => date_timestamp=$date_timestamp date_r=$date_r"

if [[ -z "$commit" ]]; then
    exit 0
fi

git checkout -b "$temp_branch" "$commit"
GIT_COMMITTER_DATE="$date_timestamp" GIT_AUTHOR_DATE="$date_timestamp" git commit --amend --no-edit --date "$date_r"
git checkout "$current_branch"
git rebase --autostash --committer-date-is-author-date "$commit" --onto "$temp_branch"
git branch -d "$temp_branch"

